# Generated by Django 5.0 on 2023-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custid', models.CharField(max_length=20)),
                ('custname', models.CharField(max_length=100)),
                ('custaddress', models.CharField(max_length=1000)),
                ('meterno', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
